"""update-appointments-leads-notes-tables

Revision ID: 56bf4062ea42
Revises: cdf13cac773b
Create Date: 2020-02-15 08:01:24.128432

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '56bf4062ea42'
down_revision = 'cdf13cac773b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('lead_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'appointments', 'leads', ['lead_id'], ['id'])
    op.add_column('notes', sa.Column('appointment', sa.Integer(), nullable=True))
    op.add_column('notes', sa.Column('lead_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'notes', 'leads', ['lead_id'], ['id'])
    op.create_foreign_key(None, 'notes', 'appointments', ['appointment'], ['id'])
    op.alter_column('tasks', 'title',
               existing_type=mysql.VARCHAR(length=60),
               nullable='False')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'title',
               existing_type=mysql.VARCHAR(length=60),
               nullable=True)
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.drop_column('notes', 'lead_id')
    op.drop_column('notes', 'appointment')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_column('appointments', 'lead_id')
    # ### end Alembic commands ###
