"""update-comments-clients-tasks-tables

Revision ID: 581805d6621a
Revises: fa2ef2780e1f
Create Date: 2020-02-19 09:18:46.116874

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '581805d6621a'
down_revision = 'fa2ef2780e1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comments_ibfk_3', 'comments', type_='foreignkey')
    op.drop_column('comments', 'client_id')
    op.add_column('tasks', sa.Column('inquiry_id', sa.Integer(), nullable=True))
    op.drop_constraint('tasks_ibfk_1', 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'inquiries', ['inquiry_id'], ['id'])
    op.drop_column('tasks', 'client_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('client_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key('tasks_ibfk_1', 'tasks', 'clients', ['client_id'], ['id'])
    op.drop_column('tasks', 'inquiry_id')
    op.add_column('comments', sa.Column('client_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('comments_ibfk_3', 'comments', 'clients', ['client_id'], ['id'])
    # ### end Alembic commands ###
