"""update-users-table

Revision ID: 6953c580dceb
Revises: d5ca9ceebc0d
Create Date: 2020-02-19 12:27:25.179516

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6953c580dceb'
down_revision = 'd5ca9ceebc0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_inquiry_links')
    op.add_column('inquiries', sa.Column('assignee', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'inquiries', 'users', ['assignee'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inquiries', type_='foreignkey')
    op.drop_column('inquiries', 'assignee')
    op.create_table('user_inquiry_links',
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('inquiry_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['inquiry_id'], ['inquiries.id'], name='user_inquiry_links_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_inquiry_links_ibfk_2'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
