"""update appointments-table

Revision ID: 6971b18293e3
Revises: 012c894422fe
Create Date: 2020-02-20 15:06:17.493258

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6971b18293e3'
down_revision = '012c894422fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('time', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
