"""update-clients-table

Revision ID: 83e66e7e23ec
Revises: b3a2498c3fb7
Create Date: 2020-02-27 11:45:57.822101

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '83e66e7e23ec'
down_revision = 'b3a2498c3fb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'type',
               existing_type=mysql.ENUM('client', 'lead'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'type',
               existing_type=mysql.ENUM('client', 'lead'),
               nullable=False)
    # ### end Alembic commands ###
