"""update-appointments-table

Revision ID: 8b198f9fcc34
Revises: 8b741a802cc3
Create Date: 2020-02-19 15:25:23.977442

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8b198f9fcc34'
down_revision = '8b741a802cc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointments', 'time',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointments', 'time',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
