"""update-inquiries-tasks-tables

Revision ID: 8b741a802cc3
Revises: 6c7b52d82c26
Create Date: 2020-02-19 14:45:45.942244

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8b741a802cc3'
down_revision = '6c7b52d82c26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_inquiries_title', table_name='inquiries')
    op.drop_column('inquiries', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inquiries', sa.Column('title', mysql.VARCHAR(length=60), nullable=False))
    op.create_index('ix_inquiries_title', 'inquiries', ['title'], unique=False)
    # ### end Alembic commands ###
