"""update-appointments-table

Revision ID: b63f6e5cc8e2
Revises: 56bf4062ea42
Create Date: 2020-02-15 08:02:42.905122

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b63f6e5cc8e2'
down_revision = '56bf4062ea42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('appointment_id', sa.Integer(), nullable=True))
    op.drop_constraint('notes_ibfk_3', 'notes', type_='foreignkey')
    op.create_foreign_key(None, 'notes', 'appointments', ['appointment_id'], ['id'])
    op.drop_column('notes', 'appointment')
    op.alter_column('tasks', 'title',
               existing_type=mysql.VARCHAR(length=60),
               nullable='False')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'title',
               existing_type=mysql.VARCHAR(length=60),
               nullable=True)
    op.add_column('notes', sa.Column('appointment', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.create_foreign_key('notes_ibfk_3', 'notes', 'appointments', ['appointment'], ['id'])
    op.drop_column('notes', 'appointment_id')
    # ### end Alembic commands ###
