"""update-comments-table

Revision ID: cae41e68b82e
Revises: de596fcb1c7e
Create Date: 2020-02-14 12:58:33.553047

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cae41e68b82e'
down_revision = 'de596fcb1c7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('customer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'customers', ['customer_id'], ['id'])
    op.alter_column('tasks', 'title',
               existing_type=mysql.VARCHAR(length=60),
               nullable='False')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'title',
               existing_type=mysql.VARCHAR(length=60),
               nullable=True)
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'customer_id')
    # ### end Alembic commands ###
