"""update-clients-table

Revision ID: d5ca9ceebc0d
Revises: 830928e41c1d
Create Date: 2020-02-19 09:40:35.897544

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd5ca9ceebc0d'
down_revision = '830928e41c1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'email',
               existing_type=mysql.VARCHAR(length=60),
               nullable=True)
    op.drop_index('tel', table_name='clients')
    op.drop_column('clients', 'tel')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('tel', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_index('tel', 'clients', ['tel'], unique=True)
    op.alter_column('clients', 'email',
               existing_type=mysql.VARCHAR(length=60),
               nullable=False)
    # ### end Alembic commands ###
