"""update appointments-table

Revision ID: d6b4b4128121
Revises: 6971b18293e3
Create Date: 2020-02-20 15:25:33.650126

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd6b4b4128121'
down_revision = '6971b18293e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('start', sa.DateTime(), nullable=False))
    op.drop_column('appointments', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('date', mysql.DATETIME(), nullable=False))
    op.drop_column('appointments', 'start')
    # ### end Alembic commands ###
