"""update-appointments-table

Revision ID: de596fcb1c7e
Revises: da2c15f5600a
Create Date: 2020-02-14 12:57:19.285150

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'de596fcb1c7e'
down_revision = 'da2c15f5600a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('customer_id', sa.Integer(), nullable=False))
    op.drop_constraint('appointments_ibfk_1', 'appointments', type_='foreignkey')
    op.create_foreign_key(None, 'appointments', 'customers', ['customer_id'], ['id'])
    op.drop_column('appointments', 'lead_id')
    op.alter_column('tasks', 'title',
               existing_type=mysql.VARCHAR(length=60),
               nullable='False')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'title',
               existing_type=mysql.VARCHAR(length=60),
               nullable=False)
    op.add_column('appointments', sa.Column('lead_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.create_foreign_key('appointments_ibfk_1', 'appointments', 'leads', ['lead_id'], ['id'])
    op.drop_column('appointments', 'customer_id')
    # ### end Alembic commands ###
