"""update-comments-table

Revision ID: fa2ef2780e1f
Revises: ae80387ec2a3
Create Date: 2020-02-19 09:17:20.213810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa2ef2780e1f'
down_revision = 'ae80387ec2a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('inquiry_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'inquiries', ['inquiry_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'inquiry_id')
    # ### end Alembic commands ###
